project:
  type: website

website:
  title: "Learning-Stan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Statistical Rethinking
        file: rethinking/index.qmd


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute: 
  cache: true
  warning: false
  message: false 

knitr: 
   opts_chunk: 
     results: 'hide'

